using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace ADODOTNET_Concepts_WebApplication
{
    public partial class SqlCommandBuilderWebForm : System.Web.UI.Page
    {
        string cs = ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString;
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void btnGetStudent_Click(object sender, EventArgs e)
        {
            using (SqlConnection con = new SqlConnection(cs))
            {
                string query = "SELECT * FROM tblStudents WHERE ID = @StudentID";
                SqlDataAdapter da = new SqlDataAdapter(query, con);
                da.SelectCommand.Parameters.AddWithValue("@StudentID", Convert.ToInt32(txtStudentID.Text));
                DataSet ds = new DataSet();

                // Giving a name to table/dataset we are fetching from database
                da.Fill(ds, "Students");

                // Storing dataset in viewstate 
                ViewState["DATASET"] = ds;

                if (ds.Tables["Students"].Rows.Count > 0)
                {
                    DataRow row = ds.Tables["Students"].Rows[0];
                    txtStudentName.Text = row["Name"].ToString();
                    txtTotalMarks.Text = row["TotalMarks"].ToString();
                    ddlGender.SelectedValue = row["Gender"].ToString();
                }
                else
                {
                    lblStatus.ForeColor = Color.Red;
                    lblStatus.Text = "No student's record by ID = " + txtStudentID.Text;
                }
            }
        }

        protected void btnUpdate_Click(object sender, EventArgs e)
        {
            using (SqlConnection con = new SqlConnection(cs))
            { 
                SqlDataAdapter da = new SqlDataAdapter("SELECT * FROM tblStudents", con);
                SqlCommandBuilder builder = new SqlCommandBuilder(da);
                DataSet ds = (DataSet)ViewState["DATASET"];
               
                if (ds.Tables["Students"].Rows.Count > 0)
                {
                    DataRow row = ds.Tables["Students"].Rows[0];
                    row["Name"] = txtStudentName.Text;
                    row["TotalMarks"] = txtTotalMarks.Text;
                    row["Gender"] = ddlGender.SelectedValue;
                }

                int rowsUpdated = da.Update(ds, "Students");
                if(rowsUpdated > 0)
                {
                    lblStatus.ForeColor = Color.Green;
                    lblStatus.Text = rowsUpdated.ToString() + " row(s) updated.";
                }
                else
                {
                    lblStatus.ForeColor = Color.Red;
                    lblStatus.Text = "No row(s) updated.";
                }
                /*
                 * To see the autogenerated INSERT, UPDATE, and DELETE T - SQL statements, 
                 * use GetInsertCommand(), GetUpdateCommand() and GetDeleteCommand().
                 */
                lblAutoGeneratedCommandSection.Text = "Auto Generated Insert, Update and Delete Command by SqlCommndBuilder";
                lblInsert.Text = builder.GetInsertCommand().CommandText;
                lblUpdate.Text = builder.GetUpdateCommand().CommandText;
                lblDelete.Text = builder.GetDeleteCommand().CommandText;
            }
        }
    }
}