<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SqlCommandBuilderWebForm.aspx.cs" Inherits="ADODOTNET_Concepts_WebApplication.SqlCommandBuilderWebForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <div style="font-family: Arial">
                <table border="1">
                    <tr>
                        <td>Student ID
                        </td>
                        <td>
                            <asp:TextBox ID="txtStudentID" runat="server" TextMode="Number"></asp:TextBox>
                            <asp:Button ID="btnGetStudent" runat="server" Text="Load"
                                OnClick="btnGetStudent_Click" />
                        </td>
                    </tr>
                    <tr>
                        <td>Name
                        </td>
                        <td>
                            <asp:TextBox ID="txtStudentName" runat="server"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td>Gender
                        </td>
                        <td>
                            <asp:DropDownList ID="ddlGender" runat="server">
                                <asp:ListItem Text="Select Gender" Value="-1"></asp:ListItem>
                                <asp:ListItem Text="Male" Value="Male"></asp:ListItem>
                                <asp:ListItem Text="Female" Value="Female"></asp:ListItem>
                            </asp:DropDownList>
                        </td>
                    </tr>
                    <tr>
                        <td>Total Marks
                        </td>
                        <td>
                            <asp:TextBox ID="txtTotalMarks" runat="server"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <asp:Button ID="btnUpdate" runat="server" Text="Update"
                                OnClick="btnUpdate_Click" />
                            <asp:Label ID="lblStatus" runat="server" Font-Bold="true">
                            </asp:Label>
                        </td>
                    </tr>
                </table>
            </div>
            <br />
            <br />
            <div>
                <h3><asp:Label ID="lblAutoGeneratedCommandSection" runat="server"></asp:Label></h3>
                <h4>Auto Generated Insert Command</h4>
                <asp:Label ID="lblInsert" runat="server"></asp:Label>
                <br />
                <br />
                <h4>Auto Generated Update Command</h4>
                <asp:Label ID="lblUpdate" runat="server"></asp:Label>
                <br />
                <br />
                <h4>Auto Generated Delete Command</h4>
                <asp:Label ID="lblDelete" runat="server"></asp:Label>
            </div>
        </div>
    </form>
</body>
</html>
